# Generated by Django 5.2 on 2025-05-02 20:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CreditList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=14)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('amount_due', models.PositiveIntegerField()),
                ('sales_agent', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('produce_name', models.CharField(max_length=100)),
                ('produce_type', models.CharField(max_length=100)),
                ('tonnage_kg', models.PositiveIntegerField()),
                ('dispatch_date', models.DateField(default=django.utils.timezone.now)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreditSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=14)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('amount_due', models.PositiveIntegerField()),
                ('sales_agent', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('produce_name', models.CharField(max_length=100)),
                ('produce_type', models.CharField(max_length=100)),
                ('tonnage_kg', models.CharField(max_length=225)),
                ('dispatch_date', models.DateField(default=django.utils.timezone.now)),
                ('branch_name', models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(max_length=100)),
                ('produce_type', models.CharField(choices=[('beans', 'Beans'), ('maize', 'Grain Maize'), ('cowpeas', 'Cowpeas'), ('gnuts', 'G-nuts'), ('rice', 'Rice'), ('soybeans', 'Soybeans')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('tonnage_kg', models.PositiveIntegerField()),
                ('cost_ugx', models.PositiveIntegerField()),
                ('dealer_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(choices=[('Matugga', 'Matugga'), ('Maganjo', 'Maganjo')], max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('selling_price_ugx', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('Dealer', 'Individual Dealer'), ('Company', 'Company'), ('Maganjo Farm', 'Maganjo Farm'), ('Matugga Farm', 'Matugga Farm')], default='Dealer', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Cereals', 'Cereals'), ('Legumes', 'Legumes'), ('Roots', 'Roots')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produce_type', models.CharField(max_length=255)),
                ('dealer', models.CharField(max_length=255)),
                ('quantity_in_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(blank=True, max_length=100, null=True)),
                ('produce_type', models.CharField(max_length=100)),
                ('unit_price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Cereals', 'Cereals'), ('Legumes', 'Legumes'), ('Roots', 'Roots')], max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock_level', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(max_length=100)),
                ('tonnage_kg', models.PositiveIntegerField()),
                ('amount_paid', models.PositiveIntegerField()),
                ('buyer_name', models.CharField(max_length=100)),
                ('sales_agent', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('branch_name', models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], default='Matugga', max_length=50)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=10)),
                ('amount_due', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('branch_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('issued_by', models.CharField(max_length=100)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kglapp.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
