# Generated by Django 5.2 on 2025-05-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0002_sales_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditList',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
