# Generated by Django 5.2 on 2025-05-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0003_delete_creditlist_delete_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AlterField(
            model_name='procurement',
            name='category',
            field=models.CharField(blank=True, choices=[('Cereals', 'Cereals'), ('Legumes', 'Legumes')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='produce_type',
            field=models.CharField(choices=[('Beans', 'Beans'), ('Maize', 'Grain Maize'), ('Cowpeas', 'Cowpeas'), ('G.nuts', 'G.nuts'), ('Soybeans', 'Soybeans')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
    ]
