# Generated by Django 4.2.20 on 2025-05-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0007_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
